config/routes.rb
Rails.application.routes.draw do
  # endpoint that specifies where we want out root page of the application to be directed to
  root "static_pages#landing_page"
  # removes static_pages from the URL and only shows privacy_policy
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def landing_page
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ELearningPlatform</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/landing_page.html.erb
<h1>StaticPages#landing_page</h1>
<p>Find me in app/views/static_pages/landing_page.html.erb</p>
<%= link_to "Privacy Policy", privacy_policy_path%>

app/views/static_pages/privacy_policy.html.erb
<h1>StaticPages#privacy_policy</h1>
<p>Find me in app/views/static_pages/privacy_policy.html.erb</p>
<%= link_to "Home", root_path %>